/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadPolicyRouteImport } from './routes/upload-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsJobIdRouteImport } from './routes/results.$jobId'
import { Route as ProcessJobIdRouteImport } from './routes/process.$jobId'
import { Route as EditJobIdRouteImport } from './routes/edit.$jobId'

const UploadPolicyRoute = UploadPolicyRouteImport.update({
  id: '/upload-policy',
  path: '/upload-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsJobIdRoute = ResultsJobIdRouteImport.update({
  id: '/results/$jobId',
  path: '/results/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessJobIdRoute = ProcessJobIdRouteImport.update({
  id: '/process/$jobId',
  path: '/process/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditJobIdRoute = EditJobIdRouteImport.update({
  id: '/edit/$jobId',
  path: '/edit/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upload-policy': typeof UploadPolicyRoute
  '/edit/$jobId': typeof EditJobIdRoute
  '/process/$jobId': typeof ProcessJobIdRoute
  '/results/$jobId': typeof ResultsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upload-policy': typeof UploadPolicyRoute
  '/edit/$jobId': typeof EditJobIdRoute
  '/process/$jobId': typeof ProcessJobIdRoute
  '/results/$jobId': typeof ResultsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upload-policy': typeof UploadPolicyRoute
  '/edit/$jobId': typeof EditJobIdRoute
  '/process/$jobId': typeof ProcessJobIdRoute
  '/results/$jobId': typeof ResultsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/history'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/upload-policy'
    | '/edit/$jobId'
    | '/process/$jobId'
    | '/results/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/history'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/upload-policy'
    | '/edit/$jobId'
    | '/process/$jobId'
    | '/results/$jobId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/history'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/upload-policy'
    | '/edit/$jobId'
    | '/process/$jobId'
    | '/results/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  HistoryRoute: typeof HistoryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UploadPolicyRoute: typeof UploadPolicyRoute
  EditJobIdRoute: typeof EditJobIdRoute
  ProcessJobIdRoute: typeof ProcessJobIdRoute
  ResultsJobIdRoute: typeof ResultsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-policy': {
      id: '/upload-policy'
      path: '/upload-policy'
      fullPath: '/upload-policy'
      preLoaderRoute: typeof UploadPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$jobId': {
      id: '/results/$jobId'
      path: '/results/$jobId'
      fullPath: '/results/$jobId'
      preLoaderRoute: typeof ResultsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process/$jobId': {
      id: '/process/$jobId'
      path: '/process/$jobId'
      fullPath: '/process/$jobId'
      preLoaderRoute: typeof ProcessJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$jobId': {
      id: '/edit/$jobId'
      path: '/edit/$jobId'
      fullPath: '/edit/$jobId'
      preLoaderRoute: typeof EditJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  HistoryRoute: HistoryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UploadPolicyRoute: UploadPolicyRoute,
  EditJobIdRoute: EditJobIdRoute,
  ProcessJobIdRoute: ProcessJobIdRoute,
  ResultsJobIdRoute: ResultsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
